# SPDX-License-Identifier: GPL-2.0-only

tenstorrent-y := \
	module.o \
	blackhole.o \
	enumerate.o \
	interrupt.o \
	hwmon.o \
	module.o \
	sg_helpers.o \
	tt_pci_drv.o \
	chardev.o \
	grayskull.o \
	memory.o \
	wormhole.o

obj-$(CONFIG_DRM_ACCEL_TT) = tenstorrent.o
